### PR TITLE
add bower manifest file

### PR DESCRIPTION
**Pull request by FourStacks**
Hi @renvrant 

Great little plugin  -  thanks for sharing!  If you're open to a PR then I thought it might be nice to have this on Bower?  Should be good to go - all you'll have to do is run:

bower register conditionize  https://github.com/renvrant/conditionize.js

### CODE REVIEW

**Comment by cmkshaw** [comment]
:+1:

**Comment by renvrant** [comment]
Hey @FourStacks, thanks so much! I hadn't even thought of including it on Bower. Will happily merge your change in!

**Comment by FourStacks** [comment]
Thanks @renvrant!

**Comment by FourStacks** [comment]
Hi again!  Just to let you know I've registered the package on bower but as they want all packages to adhere to semver tagging then you'll need to release a valid semver tag to get bower to recognise that there's a new (and currently single) release available.  After that it should be listed under search on bower.

Cheers!

**Pull request merged**
